version: 2.1

jobs:
  fail-successfully:
    docker:
      - image: alpine
    steps:
      - run: return 1

workflows:
  PR-not-allowed-in-master:
    jobs:
      - fail-successfully
    only:
      - master
