version: 2.1

jobs:
  fail-successfully:
    docker:
      - image: alpine
    steps:
      - run: return 1
  pass:
    docker:
      - image: alpine
    steps:
      - run: return 0

workflows:
  some-check:
    jobs:
      - pass
  PR-not-allowed-in-master:
    jobs:
      - fail-successfully:
          filters:
            branches:
              only:
                - master
              ignore:
                - main
